<?xml version="1.0"?>
<robot name="gazebo1" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="width" value="0.2" />
  <xacro:property name="leglen" value="0.6" />
  <xacro:property name="polelen" value="0.2" />
  <xacro:property name="bodylen" value="0.6" />
  <xacro:property name="baselen" value="0.4" />
  <xacro:property name="wheeldiam" value="0.07" />
  <xacro:property name="pi" value="3.1415" />
  <xacro:property name="ped_height" value="0.8" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
      <origin xyz="0 0 ${0.6+ped_height}"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>


  <xacro:macro name="arm" params="prefix reflect">
    <link name="${prefix}_arm">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="10"/>
        <inertia ixx="0.308" ixy="0.0" ixz="0.0" iyy="0.04" iyz="0.0" izz="0.333"/>
      </inertial>
      <visual>
        <geometry>
          <box size="${leglen} 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${leglen/2} 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen+ped_height}" rpy="0 ${pi/2} 0"/>
      </collision>
     
    </link>

    <joint name="base_to_${prefix}_arm" type="revolute">
      <axis xyz="1 0 0"/>
      <limit effort="50000.0" lower="0.0" upper="${reflect *3}" velocity="0.000001"/>
      <origin rpy="0 0 0" xyz="0 ${reflect*(width+.02)} ${0.85+ped_height}" />
      <parent link="base_link"/>
      <child link="${prefix}_arm"/>   
      <dynamics damping="0.1" friction="0"/>
    </joint>

    
  </xacro:macro>
  <xacro:arm prefix="right" reflect="-1" />
  <xacro:arm prefix="left" reflect="1" />




    <xacro:macro name="leg" params="prefix reflect">
    <link name="${prefix}_leg">
      <visual>
        <geometry>
          <box size="0.8 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.8 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="base_to_${prefix}_leg" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_leg"/>
      <origin xyz="0 ${reflect*0.1} ${0.25+ped_height}" />
    </joint>

    
  </xacro:macro>
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />


 

  <link name="head">
    <visual>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>

  <joint name="head_swivel" type="continuous">
    <parent link="base_link"/>
    <child link="head"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${1.1+ped_height}"/>
  </joint>



  <link name="aruco1">
    <visual>
      <origin rpy="0 ${pi/2} 0" xyz="0.1 0 ${-0.5}"/>
      <geometry>
        <mesh filename="package://mannequin/meshes/arucotag1.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="aruco1_joint" type="fixed">
    <parent link="left_arm"/>
    <child link="aruco1"/>
  </joint>


    <link name="pedistal">
      <visual>
        <geometry>
          <box size="0.5 0.3 0.8"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.5 0.3 ${ped_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="leg_pedistal" type="fixed">
      <parent link="base_link"/>
      <child link="pedistal"/>
      <origin xyz="0 0 0" />
    </joint>

<!--    <link name="aruco2">
    <visual>
      <origin rpy="0 ${pi/2} 0" xyz="0.1 0 -0.1"/>
      <geometry>
        <mesh filename="package://urdf_tutorial/meshes/arucotag1.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="aruco2_joint" type="fixed">
    <parent link="left_arm"/>
    <child link="aruco2"/>
  </joint>
 -->

  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>


    <gazebo reference="base_link">
    <mu1>0</mu1>
    <mu2>0</mu2>
    <fdir1 value = "1 0 0"/>
 <dynamics damping="0.7" friction="100.0" />
    <material>Gazebo/Black</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

</robot>
