<?xml version="1.0"?>
<robot name="gazebo1" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="width" value="0.2" />
  <xacro:property name="leglen" value="0.6" />
  <xacro:property name="polelen" value="0.2" />
  <xacro:property name="bodylen" value="0.6" />
  <xacro:property name="baselen" value="0.4" />
  <xacro:property name="wheeldiam" value="0.07" />
  <xacro:property name="pi" value="3.1415" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  
  <gazebo reference="base_link">
   <turnGravityOn>true</turnGravityOn>
  </gazebo>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
      <origin xyz="0 0 0.6"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>


  <xacro:macro name="arm" params="prefix reflect">
    <link name="${prefix}_arm">
      <visual>
        <geometry>
          <box size="${leglen} 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${leglen/2} 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen}" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="base_to_${prefix}_arm" type="revolute">
      <axis xyz="1 0 0"/>
      <limit effort="50.0" lower="0.0" upper="${reflect *3}" velocity="1"/>
      <origin rpy="0 0 0" xyz="0 ${reflect*(width+.02)} 0.85" />
      <parent link="base_link"/>
      <child link="${prefix}_arm"/>   
    </joint>

    
  </xacro:macro>
  <xacro:arm prefix="right" reflect="-1" />
  <xacro:arm prefix="left" reflect="1" />




    <xacro:macro name="leg" params="prefix reflect">
    <link name="${prefix}_leg">
      <visual>
        <geometry>
          <box size="0.8 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.8 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="base_to_${prefix}_leg" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_leg"/>
      <origin xyz="0 ${reflect*0.1} 0.25" />
    </joint>

    
  </xacro:macro>
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />


 

  <link name="head">
    <visual>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${width}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>

  <joint name="head_swivel" type="continuous">
    <parent link="base_link"/>
    <child link="head"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 1.1"/>
  </joint>



  <link name="aruco1">
    <visual>
      <origin rpy="0 ${pi/2} 0" xyz="0.1 0 -0.5"/>
      <geometry>
        <mesh filename="package://aruco_planning/meshes/arucotag1.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="aruco1_joint" type="fixed">
    <parent link="left_arm"/>
    <child link="aruco1"/>
  </joint>


   <link name="aruco2">
    <visual>
      <origin rpy="0 ${pi/2} 0" xyz="0.1 0 -0.1"/>
      <geometry>
        <mesh filename="package://aruco_planning/meshes/arucotag1.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="aruco2_joint" type="fixed">
    <parent link="left_arm"/>
    <child link="aruco2"/>
  </joint>


  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

</robot>
